version: '3.4'

services:
  myhomeautomation.webapi:
    image: myhomeautomationwebapi
    logging:
      options: 
        max-size: "5m"
    build:
      context: .
      dockerfile: ./MyHomeAutomation.WebApi/Dockerfile
      
  myhomeautomation.webapp:
    image: myhomeautomationwebapp
    build:
      context: .
      dockerfile: ./MyHomeAutomation.WebApp/Dockerfile
      
  myhomeautomation.db:
    image: postgres
    restart: always