version: '3.4'

services:
  myhomeautomation.webapi:
    image: myhomeautomationwebapi
    build:
      context: .
      dockerfile: ./MyHomeAutomation.WebApi/Dockerfile.ArmV7
      
  myhomeautomation.webapp:
    image: myhomeautomationwebapp
    build:
      context: ./MyHomeAutomation.WebApp/
      dockerfile: ./MyHomeAutomation.WebApp/Dockerfile
      
  myhomeautomation.db:
    image: myhomeautomationdb
    build:
      context: .
      dockerfile: ./db/Dockerfile