version: '3.4'

services:
  myhomeautomation.webapi:
    image: myhomeautomationwebapi
    build:
      context: .
      dockerfile: ./MyHomeAutomation.WebApi/Dockerfile.ArmV7
      
  myhomeautomation.webapp:
    image: myhomeautomationwebapp
    build:
      context: .
      dockerfile: ./MyHomeAutomation.WebApp/Dockerfile
      
  myhomeautomation.db:
    image: postgres:15
    restart: always