version: '3.4'

services:
  myhomeautomation.webapi:
    image: dotchcz/myhomeautomation.webapi:latest
    environment:
      - ConnectionStrings__MyHomeAutomationConn=Server=myhomeautomation.db;Database=myHomeAutomation;Port=5432;User Id=postgres;Password=raspberry;
    depends_on:
      - myhomeautomation.db
    logging:
      driver: json-file
      options:
        max-size: "50m"
    restart: always
    ports:
      - "5266:5266"
    networks:
      - myhomeautomation-dev
  myhomeautomation.webapp:
    image: dotchcz/myhomeautomation.webapp:latest
    ports:
      - "80:80"
    restart: always
    networks:
      - myhomeautomation-dev
  myhomeautomation.db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=raspberry
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - myhomeautomation-dev
  
networks:
  myhomeautomation-dev:
    name: myhomeautomation-dev
volumes:
  db:
    driver: local
    