apiVersion: v1
kind: Secret
metadata:
  name: myhomeautomation-secret
type: Opaque
data:
  connectionstring: U2VydmVyPW15aG9tZWF1dG9tYXRpb24tZGI7RGF0YWJhc2U9bXlIb21lQXV0b21hdGlvbjtQb3J0PTU0MzI7VXNlciBJZD1wb3N0Z3JlcztQYXNzd29yZD1yYXNwYmVycnk7
