apiVersion: v1
kind: Service
metadata:
  name: myhomeautomation-webapp
spec:
  selector:
    app: myhomeautomation-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhomeautomation-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myhomeautomation-webapp
  template:
    metadata:
      labels:
        app: myhomeautomation-webapp
    spec:
      containers:
        - name: webapp
          image: dotchcz/myhomeautomation.webapp:latest
          ports:
            - containerPort: 80
