apiVersion: v1
kind: Service
metadata:
  name: myhomeautomation-webapi
spec:
  selector:
    app: myhomeautomation-webapi
  ports:
    - protocol: TCP
      port: 5266
      targetPort: 5266
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhomeautomation-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myhomeautomation-webapi
  template:
    metadata:
      labels:
        app: myhomeautomation-webapi
    spec:
      containers:
        - name: webapi
          image: dotchcz/myhomeautomation.webapi:latest
          ports:
            - containerPort: 5266
          env:
            - name: ConnectionStrings__MyHomeAutomationConn
              #value: "Server=myhomeautomation-db;Database=myHomeAutomation;Port=5432;User Id=postgres;Password=raspberry;"
              valueFrom:
                secretKeyRef:
                  name: myhomeautomation-secret
                  key: connectionstring
