name: Docker Build and Push

on:
  push:
    branches:
      - main 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push multi-platform Docker image WebApi
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./MyHomeAutomation.WebApi/Dockerfile
        push: true
        tags: dotchcz/myhomeautomation.webapi:latest
        platforms: linux/amd64,linux/arm64/v8

    - name: Build and push multi-platform Docker image WebApi ARM
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./MyHomeAutomation.WebApi/Dockerfile.ArmV7
        push: true
        tags: dotchcz/myhomeautomation.webapi:latest_arm
        platforms: linux/arm/v7, linux/arm64/v8

    - name: Build and push multi-platform Docker image WebApp
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./MyHomeAutomation.WebApp/Dockerfile
        push: true
        tags: dotchcz/myhomeautomation.webapp:latest
        platforms: linux/amd64,linux/arm64/v8
